version: '3.8'
services:
  prueba_django:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prueba_djangoISDM
    restart: always
    volumes:
      - type: bind
        source: .
        target: /opt/back_end
    ports:
      - "8000:8000"
    environment:
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=3307
      - DJANGO_DB_NAME=prueba_django_db
      - DJANGO_DB_USER=OmarM
      - DJANGO_DB_PASSWORD=123456omar

  db:
    image: mysql:8.0
    container_name: mysql_prueba_django
    restart: always
    environment:    
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: prueba_django_db
      MYSQL_USER: OmarM
      MYSQL_PASSWORD: 123456omar
    ports:
      - "3307:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db